apiVersion: v1
kind: Service
metadata:
  name: gemini-live-bridge-svc
  namespace: gemini-bridge
  labels:
    app: gemini-live-bridge
spec:
  type: ClusterIP
  ports:
    - name: http-ws
      port: 8080
      targetPort: 8080
  selector:
    app: gemini-live-bridge
